### ISSUE TITLE
Use create_selected_dataset() in class DMCDataModule()

### ISSUE THREAD

**Issue by lxqpku** [microsoft/smart#12]
The original paper says"Datasets for downstream learning:
• Sampled Replay (for RTG): We randomly sample 10% trajectories from the full replay buffer of 1 SAC agent, resulting in a dataset of size 100K per task, with diverse return distribution".

However, in the current version of the code, the class DMCDataModule() for fine-tuning  RTG-conditioned downstream model  uses create_dataset() instead of create_selected_dataset(select_rate=0.1).
![屏幕截图 2023-11-30 202250](https://github.com/microsoft/smart/assets/45137511/e445b99a-582d-4149-a792-40a763337f82)

**Comment by ycsun2017** [comment]
Hi @lxqpku, sorry for the confusion. DMCDataModule is used to load the entire dataset for the task.
The RTG finetuning with Random Replay was done using DMCBCDataModule with --rand_select=True. 
I've updated README.md and the dmc_downstream.py to make it consistent with the paper. Please let me know if there are other questions.
